language: R
sudo: false
cache: packages

r_packages:
 - devtools
 - ade4
 - ape
 - EntropyEstimation
 - geiger
 - vegan
 - testthat
 - knitr
 - rmarkdown
 - SPECIES
 - covr

after_success:
  - Rscript -e 'library(covr); codecov(type ="all")'
