language: r
sudo: false
cache: packages
r_packages:
 - devtools
 - ade4
 - ape
 - EntropyEstimation
 - geiger
 - vegan
 - testthat
 - knitr
 - rmarkdown
bioc_packages:
 - BiocStyle
r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
