language: r
warnings_are_errors: true
cache: packages

jobs:
  include:
    - stage: Check package, code coverage and deploy pkgdown website
      os: linux
      dist: xenial
      r: release
      r_packages:
        - covr
        - pkgdown
      after_success:
        - Rscript -e 'covr::codecov(type ="all")'
        - mkdir docs
        - git fetch origin gh-pages:gh-pages                 # Comment out for release
        - git --work-tree=docs checkout gh-pages -- .        # Comment out for release
        - travis_wait 60 Rscript -e 'pkgdown::build_site()'
        - touch docs/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        keep_history: true                                   # Comment out for release
        token: $GITHUB_TOKEN
        on:
          branch: master
        local_dir: docs

notifications:
  email:
    recipients:
      - e.marcon@free.fr
